<a href="https://colab.research.google.com/github/Joshmen06/Numpy-Mini-Project/blob/main/Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
data_file='/content/makeSenseOfCensus.csv'
data=np.genfromtxt(data_file, delimiter=',',skip_header=1)
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [15]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [19]:
new_record=[[50,9,4,1,0,0,40,0]]
new_data = np.concatenate((data,new_record),axis=0)
new_data


array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [20]:
age = data[:,0]
age

array([39., 50., 38., 53., 28., 37., 49., 52., 31., 42., 37., 30., 23.,
       32., 40., 34., 25., 32., 38., 43., 40., 54., 35., 43., 59., 56.,
       19., 54., 39., 49., 23., 20., 45., 30., 22., 48., 21., 19., 31.,
       48., 31., 53., 24., 49., 25., 57., 53., 44., 41., 29., 25., 18.,
       47., 50., 47., 43., 46., 35., 41., 30., 30., 32., 48., 42., 29.,
       36., 28., 53., 49., 25., 19., 31., 29., 23., 79., 27., 40., 67.,
       18., 31., 18., 52., 46., 59., 44., 53., 49., 33., 30., 43., 57.,
       37., 28., 30., 34., 29., 48., 37., 48., 32., 76., 44., 47., 20.,
       29., 32., 17., 30., 31., 42., 24., 38., 56., 28., 36., 53., 56.,
       49., 55., 22., 21., 40., 30., 29., 19., 47., 20., 31., 35., 39.,
       28., 24., 38., 37., 46., 38., 43., 27., 20., 49., 61., 27., 19.,
       45., 70., 31., 22., 36., 64., 43., 47., 34., 33., 21., 52., 48.,
       23., 71., 29., 42., 68., 25., 44., 28., 45., 36., 39., 46., 18.,
       66., 27., 28., 51., 27., 28., 27., 21., 34., 18., 33., 44

In [21]:
max_age=age.max()
max_age

90.0

In [22]:
min_age=age.min()
min_age

17.0

In [23]:
age_mean=age.mean()
age_mean

38.051

In [24]:
age_std=age.std()
age_std

13.342803266180612

In [25]:
race=data[:,2]
race

array([4., 4., 4., 2., 2., 4., 2., 4., 4., 4., 2., 1., 4., 2., 1., 0., 4.,
       4., 4., 4., 4., 2., 2., 4., 4., 4., 4., 1., 4., 4., 4., 2., 4., 4.,
       2., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 4., 4., 4., 4., 3.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 2., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 2., 1., 4., 4., 4., 4., 4., 2., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 4.,
       4., 4., 4., 2., 4., 2., 4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 4.,
       4., 4., 4., 1., 4., 4., 4., 4., 4., 2., 4., 4., 4., 4., 4., 4., 1.,
       4., 4., 4., 4., 2., 4., 2., 4., 4., 1., 1., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 2., 2., 4., 4., 2., 4., 2., 4., 4., 2., 4.,
       4., 4., 4., 2., 4., 2., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 2., 4., 4., 4., 2., 4., 0., 1., 4., 2., 4., 4., 4., 4., 4.,
       4., 2., 2., 4., 4.

In [26]:
race_0 =race[race==0]
race_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
race_1=race[race==1]
race_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
race_2=race[race==2]
race_2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [29]:
race_3=race[race==3]
race_3

array([3., 3., 3., 3., 3., 3.])

In [30]:
race_4=race[race==4]
race_4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

In [31]:
len_0=len(race_0)
len_0

10

In [32]:
len_1=len(race_1)
len_1

27

In [34]:
len_2=len(race_2)
len_2

110

110

In [35]:
len_3=len(race_3)
len_3

6

In [36]:
len_4=len(race_4)
len_4

847

In [38]:
len_all= [len_0,len_1,len_2,len_3,len_4]
len_arr =np.array(len_all)
print('Minimum numbers of citizens in a race:',len_arr.min())


Minimum numbers of citizens in a race: 6


In [39]:
minority_race=len_3
minority_race

6

In [44]:
senior_citizen=age[age>60]
senior_citizen

array([79., 67., 76., 61., 70., 64., 71., 68., 66., 64., 90., 66., 75.,
       65., 64., 61., 65., 77., 62., 76., 63., 66., 67., 65., 62., 63.,
       80., 67., 63., 72., 62., 74., 67., 72., 69., 65., 65., 71., 70.,
       66., 65., 61., 61., 68., 64., 64., 62., 73., 72., 63., 62., 61.,
       71., 63., 63., 67., 81., 64., 67., 78., 63.])

In [46]:
working_hours= data[:,6]
working_hours_sum=np.sum(working_hours[age>60])
working_hours_sum

1917.0

In [47]:
senior_citizens_len=len(senior_citizen)
senior_citizens_len

61

In [48]:
avg_working_hours=working_hours_sum/senior_citizens_len
avg_working_hours

31.42622950819672

In [49]:
if avg_working_hours <= 25:
  print('Govt ploicy is followed')
else:
  print("Govt policy is not followed")

Govt policy is not followed


In [50]:
edu=data[:,1]
high=edu[edu>10]
low=edu[edu<=10]
print(high)
print(low)


[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [51]:
income=data[:,7]
avg_pay_high=np.mean(income[edu>10])
avg_pay_low=np.mean(income[edu<=10])
print(avg_pay_high)
print(avg_pay_low)

0.42813455657492355
0.13670133729569092
